#!/usr/bin/env bash

if [ ! -f ../../M2M/QNICE/assembler/qasm ]; then
    echo ""
    echo "ERROR: QNICE assembler ../../M2M/QNICE/assembler/qasm not found."
    echo ""
    echo "Things to try:"
    echo "1. This repository has dependencies: Did you run"
    echo "       git submodule update --init --recursive"
    echo "   after cloning the repository? If not, run it now."
    echo ""
    echo "2. Build the QNICE toolchain. Answer all questions by pressing ENTER."
    echo "       cd ../../M2M/QNICE/tools"
    echo "       ./make-toolchain.sh"
    echo ""
    exit
fi;

{
    echo "; DO NOT MANUALLY EDIT"
    echo "; AUTOGENERATED BY ./make-asm.sh"
    echo "; These constants are equal to the menu indexes defined in ../vhdl/mega65.vhd"
    echo ""
} > osm_const.asm

awk '/constant C_MENU_/ {gsub("C_MENU_", "C64_OSM_"); gsub(";", ""); printf("%-27s .EQU %s\n", $2, $6)}' ../vhdl/mega65.vhd >> osm_const.asm

../../M2M/QNICE/assembler/asm m2m-rom.asm
